### PR TITLE
New navigation bar

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by shtukas** [comment]
screen shot 2016-11-22 at 11 43 18

screen shot 2016-11-22 at 11 43 51

screen shot 2016-11-22 at 11 44 17

**Comment by alastairjardine** [comment]
The info text should follow on from the `<Stage>, Pass x of 3` text, if possible

**Comment by shtukas** [comment]
screen shot 2016-11-22 at 11 59 14

screen shot 2016-11-22 at 11 59 37

screen shot 2016-11-22 at 11 59 50

**Comment by alastairjardine** [comment]
👍

**Comment by alastairjardine** [comment]
thanks @shtukas

**Pull request merged**
