### PR TITLE
Add the ability to specify a quantity for servings

### PR DESCRIPTION
**Pull request by shtukas**
1. Implementation of the backend changes for the extended serving information
2. Updated user interface to capture all possible cases.
3. Small HTML refactoring.

### CODE REVIEW

**Comment by shtukas** [comment]
UI Before:

screen shot 2016-12-15 at 11 46 28

**Comment by shtukas** [comment]
UI After:

screen shot 2016-12-15 at 12 26 07

**Comment by shtukas** [comment]
JSON fragment from database record:
```
{"portion":"QuantityType","unit":"millilitres","quantity":{"to":1200,"from":1200}}
```

**Comment by tomrf1** [comment]
👍 looks good to me

**Pull request merged**
