### PR TITLE
Add a top banner to the curation page and code refactoring

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by shtukas** [comment]
screen shot 2016-11-14 at 08 00 54

**Comment by alastairjardine** [comment]
Ace – pleased to see this. I'll have a think about the stuff that should move into this area (after the PR is out).

'Skip this recipe' is a prime candidate

**Comment by alastairjardine** [comment]
👍

**Comment by LATaylor-guardian** [comment]
👍

**Comment by shtukas** [comment]
@alastairjardine Should have showed a bigger picture, but for the moment it is like this. (Merging now)

screen shot 2016-11-14 at 10 48 05

**Pull request merged**
