### PR TITLE
Renaming RecipeStatusPending into RecipeStatusPendingPostReady

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by tomrf1** [comment]
`RecipeStatusPendingCuration`?

**Comment by shtukas** [comment]
Yep, I thought of that, but didn't know if it sounded better. Give me a moment, I will change it :)

**Comment by tomrf1** [comment]
It makes more sense to me, others may disagree! 'Pending' implies an action is about to take place, so it seems reasonable to name the pending action. Presumably there'll be a `RecipeStatusPendingVerification` too.
Naming things is hard!

**Comment by shtukas** [comment]
No worries, your naming is much better than mine! I have pushed the update :)

**Comment by tomrf1** [comment]
👍

**Pull request merged**
