### PR TITLE
New database indices: user_events.user_email and user_events.operation_type

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by shtukas** [comment]
```
lucille11:recipeasy pascal$ ./flyway-mutation-dev-DB.sh
Running DB migrations using Flyway ...
[info] Flyway 4.0.3 by Boxfuse
[info] Database: jdbc:postgresql://localhost:5432/recipeasy (PostgreSQL 9.5)
[info] Successfully validated 9 migrations (execution time 00:00.031s)
[info] Current version of schema "public": 7
[info] Migrating schema "public" to version 8 - create index on user events user email
[info] Migrating schema "public" to version 9 - create index on user events operation type
[info] Successfully applied 2 migrations to schema "public" (execution time 00:00.061s).
```

**Comment by shtukas** [comment]
screen shot 2016-12-09 at 01 41 05

**Comment by LATaylor-guardian** [comment]
👍 Don't forget to run Flyway on PROD also.

**Comment by shtukas** [comment]
Will do after deploy. Cheers!

**Pull request merged**
