### PR TITLE
Correct a display bug: last picture caption

### PR DESCRIPTION
**Pull request by shtukas**
Correct a display bug preventing the caption of that last picture of a set of pictures to be seen.

### CODE REVIEW

**Comment by shtukas** [comment]
An example of occurrence of the bug (at the time those lines are written) can be found here: https://recipeasy.capi.gutools.co.uk/recipe/4d2a12824ae90735c817d3b38840339e

**Comment by tomrf1** [comment]
👍 if it works!

**Comment by shtukas** [comment]
@tomrf1 Interestingly, I need to push it to prod to have the confirmation because I don't get the pictures on my local. That being said, it's a trivial CSS change so in the worse case, I'll just revert it.

**Comment by shtukas** [comment]
Documenting the current (pre-change) display:

screen shot 2016-11-17 at 10 45 38

**Comment by shtukas** [comment]
Display (post change) :)

screen shot 2016-11-17 at 11 11 12

**Pull request merged**
