### PR TITLE
Reformulating the progress bar title

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by shtukas** [comment]
Before:

screen shot 2016-12-06 at 08 30 28

After:

screen shot 2016-12-06 at 08 30 43

**Comment by alastairjardine** [comment]
👎  I personall _love_ `structuration`, I really do. Our users, however, might not understand. 

What about "Stage one (structuring) completion"

**Comment by shtukas** [comment]
> Stage one (structuring) completion
Sounds perfect. Update coming !

**Comment by shtukas** [comment]
Updated! Thanks @alastairjardine

**Comment by alastairjardine** [comment]
👍

**Pull request merged**
