### PR TITLE
Making keyboard shortcuts _even more_ obvious

### PR DESCRIPTION
**Pull request by alastairjardine**
Making keyboard shortcuts _even more_ obvious.

Again again.

### CODE REVIEW

**Comment by alastairjardine** [comment]
moar-cat

**Comment by shtukas** [comment]
screen shot 2016-11-23 at 14 57 34

**Comment by shtukas** [comment]
screen shot 2016-11-23 at 14 57 29

**Comment by shtukas** [comment]
screen shot 2016-11-23 at 14 57 34

**Comment by shtukas** [comment]
:+1:

**Pull request merged**
