### PR TITLE
sets up play app

### PR DESCRIPTION
**Pull request by tsop14**

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
@tsop14 I don't think all of the files got added to your commit.

**Comment by LATaylor-guardian** [comment]
Google auth for PROD to be added tomorrow morning. @cb372 Feel free to review, merge and begin.

**Comment by tsop14** [comment]
Google oAuth added for PROD.

**Comment by tsop14** [comment]
👍 (said Luke and Chris)

**Pull request merged**
